[] respond with json error on http requests
DaoCasino/platform-back pull request #77
Opened 2020-10-19 10:18 UTC by georgiypetrov

2020-10-19 16:44 UTC, justefg approved these changes

2020-10-20 07:50 UTC, algys requested changes

2020-10-20 07:50 UTC, algys commented on server/http.go
> +		respondWithError(w, http.StatusBadRequest, err.Error())
if token expired need to respond with particular error

2020-10-20 07:51 UTC, algys commented
also please define somewhere "standard" error codes and error json structure

2020-10-21 09:33 UTC, Garik- approved these changes
я бы сделал вот такой формат ответа
{ response: data, error: null } - успешный запрос - { response: null, error: { code: num, message: text } } - ошибка, что бы в коде клиента можно было сделать централизованную обработку ответов

2020-10-21 10:00 UTC, georgiypetrov commented
> я бы сделал вот такой формат ответа
> { response: data, error: null } - успешный запрос - { response: null, error: { code: num, message: text } } - ошибка, что бы в коде клиента можно было сделать централизованную обработку ответов

сделаю

2020-10-28 11:16 UTC, algys approved these changes

2020-10-28 11:41 UTC, merged